### ISSUE TITLE
Hello! Pls help me!

### ISSUE THREAD

**Issue by Juranik** [GhostNaN/silero-webui#1]
```
(venv) C:\Users\Administrator\Desktop\silero-webui>python app.py
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\Desktop\silero-webui...
[nltk_data]   Package punkt is already up-to-date!
Using cache found in C:\Users\Administrator/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\gradio\queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\gradio\route_utils.py", line 217, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\gradio\blocks.py", line 1553, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\gradio\blocks.py", line 1191, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\gradio\utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\silero-webui\app.py", line 79, in generate
    torchaudio.save(output_file, audio, params['sample_rate'])
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\torchaudio\_backend\utils.py", line 311, in save
    backend = dispatcher(uri, format, backend)
  File "C:\Users\Administrator\Desktop\silero-webui\venv\lib\site-packages\torchaudio\_backend\utils.py", line 221, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri output.wav and format None.
```

And also where I should put other models? I wanna use other language models but I can't becuz don't know where I should put it

**Comment by GhostNaN** [comment]
I made some commits so that it might work now.

> And also where I should put other models? 

You don't. 
I have it configured to use the English "v3_en" model.
Although, you should be able to manually input the speaker, language and model id in the ```params``` variable.
You could see what available here: https://github.com/snakers4/silero-models#models-and-speakers

**Comment by ghost** [comment]
Have you tried pip install soundfile. this fixed the issue for me. if it didn't work restart the pc.

**Comment by Juranik** [comment]
Hello to every1, I'ma stopped using silero, but thx u all, I appericiate it :)

**Comment by GhostNaN** [comment]
@Juranik The AI world moves fast and this is no longer all that impressive.
I would recommend others to find something better, as I'm not using this either.
